
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../lab/data/lab_result_model.dart';
import 'package:intl/intl.dart';

class PdfService {
  Future<Uint8List> generateMedicalNote({
    required List<Map<String, dynamic>> messages,
    LabAnalysisResponse? labResult,
    required String summary,
  }) async {
    final doc = pw.Document();
    
    // Parse Lab Data if available
    final readings = labResult?.readings;

    // Strip markdown formatting for clean PDF text
    final cleanSummary = summary
        .replaceAll('**', '')
        .replaceAll('*', '')
        .replaceAll(RegExp(r'^#{1,6}\s', multiLine: true), '')
        .replaceAll(RegExp(r'^- ', multiLine: true), '• ');

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            _buildHeader(),
            pw.SizedBox(height: 20),
            
            // 1. AI Summary Section
            _buildSectionTitle('Consultation Summary'),
            pw.Text(cleanSummary, style: const pw.TextStyle(fontSize: 12)),
            pw.SizedBox(height: 20),

            // 2. Lab Results Section (if any)
            if (readings != null) ...[
               _buildSectionTitle('Lab Results (Urinalysis)'),
               _buildLabTable(readings),
               pw.SizedBox(height: 20),
            ],

            // 3. Disclaimer
            pw.Divider(),
            pw.Text(
              "Disclaimer: This certificate is generated by MDQ+ AI and is not a substitute for professional medical advice. Please consult a doctor for official diagnosis.",
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic),
            ),
          ];
        },
      ),
    );

    return doc.save();
  }

  pw.Widget _buildHeader() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text("MDQ+", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue)),
            pw.Text("Date: ${DateFormat('yyyy-MM-dd').format(DateTime.now())}"),
          ],
        ),
        pw.Text("Medical Consultation Record", style: pw.TextStyle(fontSize: 16)),
        pw.Divider(thickness: 2),
      ],
    );
  }

  pw.Widget _buildSectionTitle(String title) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
        pw.Divider(height: 10, thickness: 0.5),
        pw.SizedBox(height: 5),
      ],
    );
  }

  pw.Widget _buildLabTable(LabReading r) {
    return pw.TableHelper.fromTextArray(
      headers: ['Test', 'Value', 'Status'],
      data: [
        ['Leukocytes', r.leukocytes?.value ?? '-', _getStatus(r.leukocytes?.value)],
        ['Nitrites', r.nitrites?.value ?? '-', _getStatus(r.nitrites?.value)],
        ['Blood', r.blood?.value ?? '-', _getStatus(r.blood?.value)],
        ['Protein', r.protein?.value ?? '-', _getStatus(r.protein?.value)],
        ['Glucose', r.glucose?.value ?? '-', _getStatus(r.glucose?.value)],
        ['pH', r.ph?.value ?? '-', _getStatus(r.ph?.value)],
      ],
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.blue),
      cellStyle: const pw.TextStyle(fontSize: 10),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.center,
        2: pw.Alignment.center,
      },
    );
  }
  
  String _getStatus(String? val) {
    if (val == null) return '-';
    if (['Negative', 'Normal'].contains(val)) return 'Normal';
    return 'Abnormal'; // Simple logic
  }
}
