import os
from supabase import create_client, Client

# 1. ADD YOUR CREDENTIALS
SUPABASE_URL = "https://hzrjaquqlpkbggwdcres.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6cmphcXVxbHBrYmdnd2RjcmVzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDU0NDk4MywiZXhwIjoyMDgwMTIwOTgzfQ.2MSU8DsPL9UGR6NiAI7vdLYvlJS7PlvVQy_Ol4P-qXA" # MUST be the Service Role Key

supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

# 2. EXACT DATA RECONSTRUCTION FROM YOUR SCREENSHOT
# All passwords temporarily set to "TestPassword123!" for your dev environment.
users = [
    # --- DOCTORS ---
    {"email": "house@mediq.com", "first_name": "Dr. Gregory", "last_name": "House", "dob": "1980-01-01", "location": "Lagos, Nigeria", "role": "doctor"},
    {"email": "cuddy@mediq.com", "first_name": "Dr. Lisa", "last_name": "Cuddy", "dob": "1980-01-01", "location": "Lagos, Nigeria", "role": "doctor"},
    {"email": "wilson@mediq.com", "first_name": "Dr. James", "last_name": "Wilson", "dob": "1980-01-01", "location": "Lagos, Nigeria", "role": "doctor"},
    {"email": "elliot@mediq.com", "first_name": "Dr. Elliot", "last_name": "Reid", "dob": "1980-01-01", "location": "Lagos, Nigeria", "role": "doctor"},
    {"email": "kunle@mediq.com", "first_name": "Dr", "last_name": "Adeboye", "dob": "1980-01-01", "location": "Princeton-Plainsboro", "role": "doctor"},
    {"email": "tunde@mediq.com", "first_name": "Dr.", "last_name": "Adeboye", "dob": "1980-01-01", "location": "Princeton-Plainsboro", "role": "doctor"},

    # --- ADMINS ---
    {"email": "controller@mdqplus.com", "first_name": "Super", "last_name": "Admin", "dob": "1990-01-01", "location": None, "role": "admin"},
    {"email": "owner@mdqplus.com", "first_name": "Super", "last_name": "Admin", "dob": "1990-01-01", "location": None, "role": "admin"},

    # --- PATIENTS / TEST USERS ---
    {"email": "john@test.com", "first_name": "John", "last_name": "Ode", "dob": "2000-01-18", "location": "Ibadan", "role": "patient"},
    {"email": "james@test.com", "first_name": "James", "last_name": "Morris", "dob": "2000-12-05", "location": "Ibadan", "role": "patient"},
    {"email": "imtzz@yahoo.com", "first_name": "tayo", "last_name": "abo", "dob": "2000-01-18", "location": None, "role": "patient"},
    {"email": "kemi@test.com", "first_name": "Kemi", "last_name": "longs", "dob": "1980-01-01", "location": "Princeton-Plainsboro", "role": "patient"},
    
    
]

for u in users:
    print(f"Restoring {u['email']}...")
    try:
        # STEP A: Create verified identity in Supabase Auth
        auth_res = supabase.auth.admin.create_user({
            "email": u["email"],
            "password": "password123",
            "email_confirm": True,
            "user_metadata": {
                "role": u["role"]
            }
        })
        
        # Extract the UUID generated by Supabase Auth to link it perfectly
        new_uuid = auth_res.user.id

        # STEP B: Rebuild the profile in your public schema to match FastAPI Pydantic models
        db_res = supabase.table("users").insert({
            "first_name": u["first_name"],
            "last_name": u["last_name"],
            "email": u["email"],
            "hashed_password": "SUPABASE_MANAGED",
            "dob": u["dob"],
            "location": u["location"],
            "role": u["role"],
            "is_active": True,
            "is_banned": False
            # Note: The database will auto-generate the integer 'id' based on your sequence
        }).execute()
        
        print(f"✅ Restored: {u['email']}")

    except Exception as e:
        print(f"❌ Failed on {u['email']}: {e}")

print("\n🚀 Restoration complete. You can now log into the Flutter app.")