
from pydantic import BaseModel, ConfigDict, field_validator
from typing import Literal, Optional
from datetime import datetime, timezone


AppointmentType = Literal[
    "general_queue",
    "specialist_scheduled",
    "vip_request",
]


class SlotCreate(BaseModel):
    doctor_id: int
    start_time: datetime


class SlotResponse(BaseModel):
    id: int
    doctor_id: int
    start_time: datetime
    is_booked: bool
    model_config = ConfigDict(from_attributes=True)

    @field_validator("start_time")
    @classmethod
    def restore_utc_timezone(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)


class AppointmentCreate(BaseModel):
    slot_id: int
    notes: Optional[str] = None


class AppointmentProposeRequest(BaseModel):
    proposed_time: datetime


class AppointmentResponse(BaseModel):
    id: int
    # --- IDs (integer, relational DB PKs) ---
    # These were previously omitted, causing the Flutter model to default to 0
    # which broke the payment screen (userId: 0) and any per-appointment logic.
    doctor_id: Optional[int] = None
    patient_id: Optional[int] = None
    # Nullable only for ambiguous legacy records during the migration phase.
    appointment_type: Optional[AppointmentType] = None

    # --- Display names ---
    # doctor_name is re-purposed by doctor-side views to hold the *patient* name.
    # patient_name is always the real patient name (for patient-side views).
    doctor_name: str
    patient_name: Optional[str] = None

    status: str
    payment_status: str
    is_acknowledged: bool = False
    start_time: Optional[datetime] = None
    patient_joined_at: Optional[datetime] = None
    doctor_joined_at: Optional[datetime] = None
    consultation_started_at: Optional[datetime] = None
    no_show_marked_at: Optional[datetime] = None
    refund_status: Optional[str] = None
    refund_reference: Optional[str] = None
    refund_amount: Optional[float] = None
    refund_processed_at: Optional[datetime] = None
    notes: Optional[str] = None
    amount: float = 0.0
    has_review: bool = False
    paystack_reference: Optional[str] = None  # Generated by backend at booking time
    prescription: Optional[str] = None         # Doctor-authored prescription / medication plan

    model_config = ConfigDict(from_attributes=True)

    @field_validator(
        "start_time",
        "patient_joined_at",
        "doctor_joined_at",
        "consultation_started_at",
        "no_show_marked_at",
    )
    @classmethod
    def restore_utc_timezone(cls, value: Optional[datetime]) -> Optional[datetime]:
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)


class AppointmentUpdate(BaseModel):
    """Partial update payload — only provided fields are written."""
    prescription: Optional[str] = None


class GeneralBookRequest(BaseModel):
    notes: str


class VIPBookRequest(BaseModel):
    doctor_id: int
    notes: str
    preferred_time: str = "Morning"  # Morning / Afternoon / Evening


# --- Continuity of Care: Referral Schemas ---

class ReferralRequest(BaseModel):
    """Payload sent by the doctor to initiate a physical-hospital referral."""
    hospital_name: str                    # e.g. "Lagos Island General Hospital A&E"
    note: str                             # Brief clinical reason for referral


class ReferralResponse(AppointmentResponse):
    """Extends the standard appointment response with the generated referral note."""
    referred_hospital: Optional[str] = None
    referral_note: Optional[str] = None


class ReferralCreate(BaseModel):
    """
    Payload for POST /api/v1/appointments/referral.

    Triggers PDF generation and email dispatch of a clinical specialist referral
    on behalf of the authenticated doctor.

    Fields
    ------
    appointment_id   : The appointment this referral is attached to.
    recipient_email  : The specialist / clinic email that will receive the PDF.
    specialist_type  : E.g. 'Cardiologist', 'Neurologist', etc.
    clinical_notes   : The body text of the referral letter.
    """
    appointment_id: int
    recipient_email: str
    specialist_type: str
    clinical_notes: str
