// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7adm9agL4jeGS_3Rl0emZZXbCqIaTco',
    appId: '1:350374635163:web:56f34e0e9d118f5254083e',
    messagingSenderId: '350374635163',
    projectId: 'mdqplus-f2f81',
    authDomain: 'mdqplus-f2f81.firebaseapp.com',
    storageBucket: 'mdqplus-f2f81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRxm6_k_eYnepjhOpdOxl_O2Gcmm_b8rQ',
    appId: '1:350374635163:android:3f42d3a14fa2085354083e',
    messagingSenderId: '350374635163',
    projectId: 'mdqplus-f2f81',
    storageBucket: 'mdqplus-f2f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABeZJH1ePWtZnPfO71zqkgOiM2nw5ZnZg',
    appId: '1:350374635163:ios:fde7ab5adc715b2d54083e',
    messagingSenderId: '350374635163',
    projectId: 'mdqplus-f2f81',
    storageBucket: 'mdqplus-f2f81.firebasestorage.app',
    iosBundleId: 'com.mediq.mediqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABeZJH1ePWtZnPfO71zqkgOiM2nw5ZnZg',
    appId: '1:350374635163:ios:fde7ab5adc715b2d54083e',
    messagingSenderId: '350374635163',
    projectId: 'mdqplus-f2f81',
    storageBucket: 'mdqplus-f2f81.firebasestorage.app',
    iosBundleId: 'com.mediq.mediqApp',
  );
}
