import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'src/core/router/app_router.dart';
import 'src/core/theme/app_theme.dart';
import 'src/features/auth/presentation/user_controller.dart';
import 'src/features/auth/data/user_model.dart';
import 'src/shared/presentation/widgets/global_error_widget.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file was generated by flutterfire configure
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:supabase_flutter/supabase_flutter.dart' hide User;
// import 'package:web/web.dart' as web; // For cleaning URL (Optional)

// 🔭 Observability — Sentry (crash reporting) & PostHog (analytics)
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:posthog_flutter/posthog_flutter.dart'; // PostHog: native config in AndroidManifest/Info.plist

void main() async {
  // ---------------------------------------------------------------------------
  // 🔭 Sentry — wraps the entire app so crashes anywhere are captured.
  // Set SENTRY_DSN in your .env / CI secrets. Empty string = silent no-op.
  // ---------------------------------------------------------------------------
  await SentryFlutter.init(
    (options) {
      options.dsn = const String.fromEnvironment(
        'SENTRY_DSN',
        defaultValue: '', // Fails open — no data sent when DSN is absent
      );
      options.tracesSampleRate = 1.0;   // 100 % → lower to 0.1 in high-traffic prod
      options.profilesSampleRate = 1.0; // CPU profiling (requires tracesSampleRate > 0)
      options.debug = kDebugMode;       // Verbose Sentry logs only in debug builds
    },
    appRunner: () async {
      WidgetsFlutterBinding.ensureInitialized();

      await dotenv.load(fileName: ".env");
      await Supabase.initialize(
        url: dotenv.env['SUPABASE_URL']!,
        anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
        // Tells the Supabase SDK to intercept deep links on this scheme and
        // automatically exchange the token before firing onAuthStateChange.
        // Must match AndroidManifest.xml android:scheme value.
        authOptions: const FlutterAuthClientOptions(
          authFlowType: AuthFlowType.pkce,
        ),
      );

      // --- 🔥 Firebase Initialization ---
      try {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform, // Fix for Flutter Web
        );

        // 🛑 FIX: Removed await NotificationService().init() from the boot sequence.
        // Browsers block notification requests on load without user interaction,
        // which caused the infinite white screen. We will call this post-login instead.
      } catch (e) {
        debugPrint("Firebase init failed: $e");
      }

      // --- 🛡️ Error Boundaries ---
      // 1. Catch synchronous UI rendering errors (Grey Screen of Death)
      ErrorWidget.builder = (FlutterErrorDetails details) {
        // Only return the custom widget in release mode or if we want it in debug too.
        // We already handle kDebugMode inside GlobalErrorWidget to show the stack trace.
        return GlobalErrorWidget(details: details);
      };

      // 2. Catch asynchronous Dart exceptions — forwarded to Sentry before
      //    returning true (fail-open: the app never crashes from this handler).
      PlatformDispatcher.instance.onError = (error, stack) {
        if (kDebugMode) {
          debugPrint('🐛 [PlatformDispatcher] Asynchronous Error Caught: $error');
          debugPrint('🐛 StackTrace: $stack');
        }
        // Forward to Sentry — no-op when DSN is empty (local dev)
        Sentry.captureException(error, stackTrace: stack);
        return true; // Return true to prevent the app from crashing entirely
      };
      // ---------------------------

      runApp(const ProviderScope(child: MDQApp()));
    },
  );
}

class MDQApp extends ConsumerWidget {
  const MDQApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goRouter = ref.watch(goRouterProvider);

    // 1. Listen to the active user state (updates when you toggle settings)
    final activeUser = ref.watch(userControllerProvider).value;

    // 2. Listen to the database fetch (updates when app restarts)
    final fetchedUser = ref.watch(userProvider).value;

    // 3. Merge them (Active takes priority)
    final User? currentUser = activeUser ?? fetchedUser;

    // 4. Determine Theme
    ThemeMode currentMode = ThemeMode.system;
    if (currentUser != null) {
      if (currentUser.settingsTheme == 'dark') {
        currentMode = ThemeMode.dark;
      } else if (currentUser.settingsTheme == 'light') {
        currentMode = ThemeMode.light;
      }
    }

    return MaterialApp.router(
      title: 'MDQ+',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: currentMode,
      routerConfig: goRouter,
    );
  }
}
