import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'src/core/router/app_router.dart';
import 'src/core/theme/app_theme.dart';
import 'src/features/auth/presentation/user_controller.dart';
import 'src/features/auth/data/user_model.dart';
import 'src/features/auth/data/auth_session_coordinator.dart';
import 'src/features/auth/presentation/auth_session_lifecycle.dart';
import 'src/features/chat/presentation/consultation_session_controller.dart';
import 'src/core/services/notification_service.dart';
import 'src/features/notifications/data/notification_repository.dart';
import 'src/features/notifications/navigation/notification_intent.dart';
import 'src/features/notifications/navigation/notification_navigation_coordinator.dart';
import 'src/shared/presentation/widgets/global_error_widget.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file was generated by flutterfire configure
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:supabase_flutter/supabase_flutter.dart' hide User;
// import 'package:web/web.dart' as web; // For cleaning URL (Optional)

// 🔭 Observability — Sentry (crash reporting) & PostHog (analytics)
import 'package:sentry_flutter/sentry_flutter.dart';

const _sentryDsn = String.fromEnvironment('SENTRY_DSN', defaultValue: '');
bool _firebaseReady = false;

Future<void> main() async {
  if (_sentryDsn.trim().isEmpty) {
    await _bootstrapApplication();
    return;
  }

  if (!_isValidSentryDsn(_sentryDsn)) {
    if (kDebugMode) {
      debugPrint('Sentry disabled: invalid DSN configuration.');
    }
    await _bootstrapApplication();
    return;
  }

  var bootstrapStarted = false;
  var bootstrapCompleted = false;
  Future<void>? bootstrapFuture;

  Future<void> bootstrapOnce() {
    return bootstrapFuture ??= (() async {
      bootstrapStarted = true;
      await _bootstrapApplication();
      bootstrapCompleted = true;
    })();
  }

  try {
    await SentryFlutter.init(
      (options) {
        options.dsn = _sentryDsn;
        const sampleRate = kDebugMode ? 1.0 : 0.1;
        options.tracesSampleRate = sampleRate;
        options.profilesSampleRate = sampleRate;
        options.debug = kDebugMode;
      },
      appRunner: bootstrapOnce,
    );
  } catch (error, stackTrace) {
    // If appRunner started but did not complete, the exception came from the
    // application bootstrap itself. Preserve that failure instead of retrying
    // initialization and potentially calling runApp twice.
    if (bootstrapStarted && !bootstrapCompleted) {
      Error.throwWithStackTrace(error, stackTrace);
    }

    if (kDebugMode) {
      debugPrint('Sentry disabled: initialization failed.');
    }

    // Sentry failed before invoking appRunner. Start MDQ+ exactly once without
    // observability. If bootstrap already completed, the app is already live.
    if (!bootstrapStarted) {
      await bootstrapOnce();
    }
  }
}

bool _isValidSentryDsn(String value) {
  try {
    final dsn = Dsn.parse(value);
    final uri = dsn.uri;
    return uri != null &&
        (uri.scheme == 'https' || uri.scheme == 'http') &&
        uri.host.isNotEmpty &&
        dsn.publicKey.isNotEmpty &&
        dsn.projectId.isNotEmpty;
  } catch (_) {
    return false;
  }
}

Future<void> _bootstrapApplication() async {
  WidgetsFlutterBinding.ensureInitialized();

  await dotenv.load(fileName: ".env");
  await Supabase.initialize(
    url: dotenv.env['SUPABASE_URL']!,
    anonKey: dotenv.env['SUPABASE_ANON_KEY']!,
    // Tells the Supabase SDK to intercept deep links on this scheme and
    // automatically exchange the token before firing onAuthStateChange.
    // Must match AndroidManifest.xml android:scheme value.
    authOptions: const FlutterAuthClientOptions(
      authFlowType: AuthFlowType.pkce,
    ),
  );

  // --- 🔥 Firebase Initialization ---
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform, // Fix for Flutter Web
    );
    _firebaseReady = true;
  } catch (_) {
    debugPrint('[STARTUP] Firebase initialization failed.');
  }

  // --- 🛡️ Error Boundaries ---
  // 1. Catch synchronous UI rendering errors (Grey Screen of Death)
  ErrorWidget.builder = (FlutterErrorDetails details) {
    // The global widget always uses MDQ-owned copy and never renders raw details.
    return GlobalErrorWidget(details: details);
  };

  // 2. Catch asynchronous Dart exceptions — forwarded to Sentry before
  //    returning true (fail-open: the app never crashes from this handler).
  PlatformDispatcher.instance.onError = (error, stack) {
    if (kDebugMode) {
      debugPrint(
        '[PlatformDispatcher] asynchronous failure_type=${error.runtimeType}',
      );
    }
    // Forward to Sentry — no-op when DSN is empty (local dev)
    Sentry.captureException(error, stackTrace: stack);
    return true; // Return true to prevent the app from crashing entirely
  };
  // ---------------------------

  runApp(const ProviderScope(child: MDQApp()));
}

class MDQApp extends ConsumerStatefulWidget {
  const MDQApp({super.key});

  @override
  ConsumerState<MDQApp> createState() => _MDQAppState();
}

class _MDQAppState extends ConsumerState<MDQApp> with WidgetsBindingObserver {
  String? _registeredNotificationAccount;
  bool? _registeredPushPreference;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (kDebugMode) {
      final route = ref
          .read(goRouterProvider)
          .routerDelegate
          .currentConfiguration
          .uri
          .path;
      debugPrint('[LIFECYCLE] state=${state.name} route=$route');
    }
    ref
        .read(consultationSessionRegistryProvider)
        .handleAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      _registeredNotificationAccount = null;
      _registeredPushPreference = null;
      unawaited(_restoreAuthenticatedProfile());
    }
  }

  Future<void> _restoreAuthenticatedProfile() async {
    try {
      final token = await ref
          .read(authSessionCoordinatorProvider)
          .accessTokenIfAvailable();
      if (token != null && mounted) {
        ref.invalidate(userProvider);
      }
    } on TransientSessionRefreshException {
      // Preserve both the Supabase session and any last-known shell identity.
    } on TerminalSessionRefreshException {
      // The coordinator/Supabase auth event performs authoritative teardown.
    }
  }

  Future<void> _syncNotificationSession(
    String accountKey,
    bool pushEnabled,
  ) async {
    if (!_firebaseReady) return;
    try {
      await ref.read(notificationServiceProvider).authenticatedSessionStarted(
            accountKey: accountKey,
            pushEnabled: pushEnabled,
          );
    } catch (_) {
      if (kDebugMode) {
        debugPrint('[NOTIFICATIONS] lifecycle initialization unavailable.');
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    ref.watch(authSessionLifecycleProvider);
    final goRouter = ref.watch(goRouterProvider);

    // 1. Listen to the active user state (updates when you toggle settings)
    final activeUser = ref.watch(userControllerProvider).value;

    // 2. Listen to the database fetch (updates when app restarts)
    final fetchedUserState = ref.watch(userProvider);
    final fetchedUser = fetchedUserState.value;

    // 3. Merge them (Active takes priority)
    final User? currentUser = activeUser ?? fetchedUser;
    final session = Supabase.instance.client.auth.currentSession;
    final notificationNavigation =
        ref.read(notificationNavigationCoordinatorProvider);
    final notificationSessionReady =
        session != null && fetchedUser != null && !fetchedUserState.isLoading;

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      notificationNavigation.attachNavigator(goRouter.go);
      notificationNavigation.updateSessionReady(notificationSessionReady);
      if (_firebaseReady) {
        final service = ref.read(notificationServiceProvider);
        unawaited(service.initialize(
          onIntent: (data) {
            ref.invalidate(notificationsProvider);
            ref.invalidate(unreadNotificationCountProvider);
            notificationNavigation.submit(data);
          },
          onForegroundMessage: (message) {
            ref.invalidate(notificationsProvider);
            ref.invalidate(unreadNotificationCountProvider);
            final intent = NotificationIntent.fromData(message.data);
            final currentPath =
                goRouter.routerDelegate.currentConfiguration.uri.path;
            if (intent?.route == currentPath) return;
            rootScaffoldMessengerKey.currentState?.showSnackBar(
              SnackBar(
                content: Text(
                  message.body ??
                      message.title ??
                      'You have a new notification.',
                ),
                action: intent == null
                    ? null
                    : SnackBarAction(
                        label: 'View',
                        onPressed: () =>
                            notificationNavigation.submit(message.data),
                      ),
              ),
            );
          },
        ));
      }
    });

    if (session != null && fetchedUser != null && !fetchedUserState.isLoading) {
      final preference = fetchedUser.settingsNotifications;
      if (_registeredNotificationAccount != session.user.id ||
          _registeredPushPreference != preference) {
        _registeredNotificationAccount = session.user.id;
        _registeredPushPreference = preference;
        unawaited(_syncNotificationSession(session.user.id, preference));
      }
    } else {
      _registeredNotificationAccount = null;
      _registeredPushPreference = null;
    }

    // 4. Determine Theme
    ThemeMode currentMode = ThemeMode.system;
    if (currentUser != null) {
      if (currentUser.settingsTheme == 'dark') {
        currentMode = ThemeMode.dark;
      } else if (currentUser.settingsTheme == 'light') {
        currentMode = ThemeMode.light;
      }
    }

    return MaterialApp.router(
      scaffoldMessengerKey: rootScaffoldMessengerKey,
      title: 'MDQ+',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: currentMode,
      routerConfig: goRouter,
    );
  }
}
